### ISSUE TITLE
question

### ISSUE THREAD

**Issue by spaette** [freemin7/RocketEquation#1]
@freemin7

src/RocketEquation.jl

What's the basis for the naming of the string `attactor` which appears twice in the above file?

**Comment by freemin7** [comment]
It's some kind of simulated attractions between the the particles of the game of the unfinished prototype

**Comment by spaette** [comment]
`https://github.com/SciML/DiffEqBase.jl/issues/515`

test/downstream/community_callback_tests.jl

Is it herewith inferred that the spelling as `attactor` was intentional?

**Comment by spaette** [comment]
`https://github.com/SciML/DiffEqBase.jl/issues/515`

test/downstream/community_callback_tests.jl

Is it herewith inferred that the spelling as `attactor` was intentional?

**Comment by freemin7** [comment]
No it was supposed to read as `attractor` and that term is not even technically accurate. Thank you for pointing this out. I like the misspelling though.
May i ask why you ask so strangely?

**Comment by spaette** [comment]
> `attractor` ...that term is not even technically accurate

More was involved than a possible typo fix.

> May i ask why you ask so strangely?

Precisely, I'm unsure of what you are referring to.

**Comment by freemin7** [comment]
I won't fix it in my repo as it is not an exported api or somehow user visible and the code base would require a rewrite anyway. If you want i can edit the text in the issue you mentioned. Would that be a satisfying conclusion?

**Comment by spaette** [comment]
The DiffEqBase.jl repo's file with the code section mentions the Issue number.

It is know to the reader of that Issue what was the origin of that code section.

Nothing therefore appears indicated to be changed, edited, or commented further on.
